services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${DJANGO_SERVER_PORT}:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $DJANGO_DB_PASSWORD
      POSTGRES_USER: $DJANGO_DB_USERNAME
      POSTGRES_DB: $DJANGO_DB_DATABASE
      PGUSER: $DJANGO_DB_USERNAME
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./data_warehouse:/docker-entrypoint.d
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
    
    