# Generated by Django 3.1.14 on 2022-03-09 12:19
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_routing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpikeyPolygons',
            new_name='SpikeyPolygon',
        ),
    ]
