name: Analyze PR

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  push:

jobs:
  analyse:
    name: Analyse Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository on branch: ${{ github.REF }}"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.HEAD_REF }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Set up Build and Test Config
        run: cp .env.template .env
      - name: Start containers.
        run: docker-compose up -d
      - name: Lint with Pre-Commit on all files
        run: make pre-commit
      - name: Pytest with Coverage and Unit Test Report
        env:
          DJANGO_DB_USERNAME: postgres
          DJANGO_DB_PASSWORD: postgres
          DJANGO_DB_HOST: localhost
          DJANGO_DB_PORT: 5432
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          make test
